CREATE TABLE EmployeeInfo (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    image VARCHAR(255),
    fName VARCHAR(255),
    mName VARCHAR(255),
    lName VARCHAR(255),
    father_Name VARCHAR(255),
    CNIC VARCHAR(255),
    email VARCHAR(255),
    pAddress VARCHAR(255),
    cAddress VARCHAR(255),
    city VARCHAR(255),
    postAddress VARCHAR(255),
    mNumber VARCHAR(255),
    ofphNumber VARCHAR(255),
    Alternate_Number VARCHAR(255),
    DofB DATE,
    religion VARCHAR(255),
    gender VARCHAR(255),
    BlGroup VARCHAR(255),
    Domicile VARCHAR(255),
    MaritalStatus VARCHAR(255),
    NextofKin VARCHAR(255),
    NextofKinCellNumber VARCHAR(255),
    ContactPerson VARCHAR(255),
    CPCN VARCHAR(255),
    Employement_Group VARCHAR(255),
    Employee_Class VARCHAR(255),
    Employee_Group VARCHAR(255),
    Employee_Sub_Group VARCHAR(255),
    Employee_Quota VARCHAR(255),
    Grade_tma VARCHAR(255),
    Department VARCHAR(255),
    Job_Tiltle VARCHAR(255),
    Salary_Mode VARCHAR(255),
    Employee_Status VARCHAR(255),
    EmployeeNowssp VARCHAR(255),
    Employee_Manager VARCHAR(255),
    Joining_Date DATE,
    Contract_Expiry_Date DATE,
    Last_Working_Date DATE,
    Attendance_Supervisor VARCHAR(255),
    Duty_Location VARCHAR(255),
    Duty_Point VARCHAR(255),
    EmpGrupTma VARCHAR(255),
    Employee_Class_tma VARCHAR(255),
    Employee_Group_tma VARCHAR(255),
    Employee_Sub_Group_tma VARCHAR(255),
    Employee_Quota_tma VARCHAR(255),
    Grande_tma VARCHAR(255),
    Department_name VARCHAR(255),
    Job_Tiltle_tma VARCHAR(255),
    Salary_Mode_tma VARCHAR(255),
    Status_tma VARCHAR(255),
    EmployeeNo_tma VARCHAR(255),
    Employee_Manager_tma VARCHAR(255),
    Joining_Date_tma DATE,
    Contract_Expiry_Date_tma DATE,
    Last_Working_Day DATE,
    Attendance_Supervisor_tma VARCHAR(255),
    Duty_Location_tma VARCHAR(255),
    Duty_Point_tma VARCHAR(255),
     Status VARCHAR(255)
);


/* -------------------------------------
payroll table query
-- payroll table query
------------------------------------- */
CREATE TABLE payroll (
  id INT AUTO_INCREMENT PRIMARY KEY,
  employee_id INT,
  payment_mode VARCHAR(50),
  employee_pay_group VARCHAR(50),
  employee_pay_sub_group VARCHAR(50),
  employee_pay_classification VARCHAR(50),
  salary_bank VARCHAR(50),
  salary_branch VARCHAR(50),
  account_no VARCHAR(50),
  pay_type VARCHAR(50),
  eobi_no VARCHAR(50),
  bill_waived_off VARCHAR(50),
  working_days VARCHAR(50),
  remarks TEXT,
  fund_contrib int not null,
  gross_pay int not null,
  deduction int not null,
  net_pay int not null,
  earning_deduction_fund_description VARCHAR(100),
  allowance_calc_mode VARCHAR(50),
  earning_deduction_fund_type VARCHAR(50),
  rate int,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (employee_id) REFERENCES EmployeeInfo(Id)
);